# Generated by Django 4.2.1 on 2023-05-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='man_shop',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет товара:'),
        ),
    ]
